prs:
  swagger:
    enable: true
  gateway:
    noTokenApis:
    - /register
    - /login
  redis:
    accept-package: com.prs

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      httpclient:
        pool:
          acquire-timeout: 10000
  redis:
    host: 172.16.135.132
    port: 6379
    password: admin123

